steps:
  # Schritt 1: Abhängigkeiten installieren und das Image erstellen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pillow-http', '.']

  # Schritt 2: Das Image in die Google Container Registry pushen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pillow-http']

  # Schritt 3: Das Image in Google Cloud Run bereitstellen
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'pillow-http-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/pillow-http'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/pillow-http'
