steps:
  # Schritt 1: Abh채ngigkeiten installieren und das Image erstellen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pillow-http', '.']

  # Schritt 2: Das Image in die Google Container Registry pushen
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pillow-http']

  # Schritt 3: Das Image in Google Cloud Run bereitstellen
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'gcloud' # WICHTIG: entrypoint hinzuf체gen
    args:
      - 'run'
      - 'deploy'
      - 'pillow-http-service' # Name des Cloud Run Dienstes
      - '--image'
      - 'gcr.io/$PROJECT_ID/pillow-http'
      - '--region'
      - 'us-central1' # Deine Region
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Nur f체r Tests! In der Produktion AUTH aktivieren!
      - '--set-env-vars' # Umgebungsvariablen setzen
      - 'PORT=8080' # Port f체r die Anwendung
      - '--timeout=300s' # Timeout setzen (5 Minuten)

images:
  - 'gcr.io/$PROJECT_ID/pillow-http'
